[versions]
activity-compose = "1.9.3"
agp = "8.11.2"
kotlin = "2.2.21"
kotlinx-serialization-json = "1.7.3"
nexus-publish = "2.0.0"
android-minSdk = "24"
android-compileSdk = "34"
systemLambda = "1.2.0"
startupRuntime = "1.2.0"
compose-plugin = "1.9.1"
media3-exoplayer = "1.4.1"
compose-webview = "2.0.3"
slf4j-Simple = "2.0.13"
vlcj= "4.11.0"
composeMultiplatformMediaPlayer = "1.0.50"
vlc-setup = "0.1.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3-exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-exoplayer" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
system-lambda = { module = "com.github.stefanbirkner:system-lambda", version.ref = "systemLambda" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
kmp-compose-webview = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "compose-webview" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-Simple" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
compose-multiplatform-media-player = { module = "network.chaintech:compose-multiplatform-media-player", version.ref = "composeMultiplatformMediaPlayer" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinJs = { id = "org.jetbrains.kotlin.plugin.js", version.ref = "kotlin" }
vlc-setup = { id = "ir.mahozad.vlc-setup", version.ref = "vlc-setup" }